# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QLabel, QLayout, QMainWindow,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(986, 392)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 10, 641, 361))
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.layoutWidget_2 = QWidget(self.tab_1)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 10, 611, 311))
        self.gridLayout_5 = QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout_5.setHorizontalSpacing(6)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_106 = QLabel(self.layoutWidget_2)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_106, 7, 2, 1, 1)

        self.label_97 = QLabel(self.layoutWidget_2)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_97, 2, 2, 1, 1)

        self.label_98 = QLabel(self.layoutWidget_2)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_98, 3, 0, 1, 1)

        self.label_102 = QLabel(self.layoutWidget_2)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_102, 5, 2, 1, 1)

        self.label_110 = QLabel(self.layoutWidget_2)
        self.label_110.setObjectName(u"label_110")
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 170, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(0, 255, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(0, 212, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(0, 85, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(0, 113, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        brush7 = QBrush(QColor(127, 212, 127, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        brush8 = QBrush(QColor(255, 255, 220, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush9 = QBrush(QColor(240, 240, 240, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        brush10 = QBrush(QColor(227, 227, 227, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        brush11 = QBrush(QColor(160, 160, 160, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        brush12 = QBrush(QColor(105, 105, 105, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        brush13 = QBrush(QColor(245, 245, 245, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.label_110.setPalette(palette)
        font = QFont()
        font.setBold(True)
        self.label_110.setFont(font)
        self.label_110.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_110, 0, 0, 1, 1)

        self.label_117 = QLabel(self.layoutWidget_2)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_117, 7, 1, 1, 1)

        self.label_112 = QLabel(self.layoutWidget_2)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_112, 5, 0, 1, 1)

        self.label_118 = QLabel(self.layoutWidget_2)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_118, 4, 2, 1, 1)

        self.label_103 = QLabel(self.layoutWidget_2)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_103, 5, 1, 1, 1)

        self.label_107 = QLabel(self.layoutWidget_2)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_107, 3, 2, 1, 1)

        self.label_115 = QLabel(self.layoutWidget_2)
        self.label_115.setObjectName(u"label_115")
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush11)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush6)
        brush14 = QBrush(QColor(241, 241, 241, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush12)
        brush15 = QBrush(QColor(0, 120, 215, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Highlight, brush15)
        palette1.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        brush16 = QBrush(QColor(0, 0, 255, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Link, brush16)
        brush17 = QBrush(QColor(255, 0, 255, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.LinkVisited, brush17)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush13)
        palette1.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush18 = QBrush(QColor(0, 0, 0, 128))
        brush18.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette1.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Link, brush16)
        palette1.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush17)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        brush19 = QBrush(QColor(0, 0, 0, 255))
        brush19.setStyle(Qt.NoBrush)
        palette1.setBrush(QPalette.Inactive, QPalette.NoRole, brush19)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
#endif
        brush20 = QBrush(QColor(120, 120, 120, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        brush21 = QBrush(QColor(247, 247, 247, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush21)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush11)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.Highlight, brush15)
        palette1.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Link, brush16)
        palette1.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush17)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        brush22 = QBrush(QColor(0, 0, 0, 255))
        brush22.setStyle(Qt.NoBrush)
        palette1.setBrush(QPalette.Disabled, QPalette.NoRole, brush22)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush18)
#endif
        self.label_115.setPalette(palette1)
        self.label_115.setFont(font)
        self.label_115.setFrameShape(QFrame.NoFrame)
        self.label_115.setTextFormat(Qt.MarkdownText)
        self.label_115.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_115, 0, 1, 1, 1)

        self.label_104 = QLabel(self.layoutWidget_2)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_104, 7, 0, 1, 1)

        self.label_99 = QLabel(self.layoutWidget_2)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setFont(font)
        self.label_99.setAlignment(Qt.AlignCenter)
        self.label_99.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_99, 0, 2, 1, 1)

        self.label_100 = QLabel(self.layoutWidget_2)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_100, 3, 1, 1, 1)

        self.label_116 = QLabel(self.layoutWidget_2)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_116, 6, 2, 1, 1)

        self.label_109 = QLabel(self.layoutWidget_2)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_109, 6, 0, 1, 1)

        self.label_101 = QLabel(self.layoutWidget_2)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setScaledContents(True)
        self.label_101.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_101, 2, 1, 1, 1)

        self.label_105 = QLabel(self.layoutWidget_2)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_105, 6, 1, 1, 1)

        self.label_120 = QLabel(self.layoutWidget_2)
        self.label_120.setObjectName(u"label_120")
        self.label_120.setAlignment(Qt.AlignCenter)

        self.gridLayout_5.addWidget(self.label_120, 1, 2, 1, 1)

        self.label_114 = QLabel(self.layoutWidget_2)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_114, 4, 1, 1, 1)

        self.label_119 = QLabel(self.layoutWidget_2)
        self.label_119.setObjectName(u"label_119")
        sizePolicy.setHeightForWidth(self.label_119.sizePolicy().hasHeightForWidth())
        self.label_119.setSizePolicy(sizePolicy)
        self.label_119.setScaledContents(False)
        self.label_119.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_119, 1, 0, 1, 1)

        self.label_108 = QLabel(self.layoutWidget_2)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_108, 2, 0, 1, 1)

        self.label_111 = QLabel(self.layoutWidget_2)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_111, 4, 0, 1, 1)

        self.label_113 = QLabel(self.layoutWidget_2)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setScaledContents(True)
        self.label_113.setWordWrap(True)

        self.gridLayout_5.addWidget(self.label_113, 1, 1, 1, 1)

        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.layoutWidget_3 = QWidget(self.tab_2)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(10, 10, 611, 311))
        self.gridLayout_4 = QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout_4.setHorizontalSpacing(6)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_89 = QLabel(self.layoutWidget_3)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setScaledContents(True)
        self.label_89.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_89, 1, 1, 1, 1)

        self.label_94 = QLabel(self.layoutWidget_3)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_94, 4, 2, 1, 1)

        self.label_78 = QLabel(self.layoutWidget_3)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_78, 5, 2, 1, 1)

        self.label_76 = QLabel(self.layoutWidget_3)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_76, 3, 1, 1, 1)

        self.label_96 = QLabel(self.layoutWidget_3)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_96, 1, 2, 1, 1)

        self.label_77 = QLabel(self.layoutWidget_3)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setScaledContents(True)
        self.label_77.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_77, 2, 1, 1, 1)

        self.label_74 = QLabel(self.layoutWidget_3)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_74, 3, 0, 1, 1)

        self.label_83 = QLabel(self.layoutWidget_3)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_83, 3, 2, 1, 1)

        self.label_85 = QLabel(self.layoutWidget_3)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_85, 6, 0, 1, 1)

        self.label_90 = QLabel(self.layoutWidget_3)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_90, 4, 1, 1, 1)

        self.label_79 = QLabel(self.layoutWidget_3)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_79, 5, 1, 1, 1)

        self.label_87 = QLabel(self.layoutWidget_3)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_87, 4, 0, 1, 1)

        self.label_95 = QLabel(self.layoutWidget_3)
        self.label_95.setObjectName(u"label_95")
        sizePolicy.setHeightForWidth(self.label_95.sizePolicy().hasHeightForWidth())
        self.label_95.setSizePolicy(sizePolicy)
        self.label_95.setScaledContents(False)
        self.label_95.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_95, 1, 0, 1, 1)

        self.label_88 = QLabel(self.layoutWidget_3)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_88, 5, 0, 1, 1)

        self.label_73 = QLabel(self.layoutWidget_3)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_73, 2, 2, 1, 1)

        self.label_92 = QLabel(self.layoutWidget_3)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_92, 6, 2, 1, 1)

        self.label_86 = QLabel(self.layoutWidget_3)
        self.label_86.setObjectName(u"label_86")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.label_86.setPalette(palette2)
        self.label_86.setFont(font)
        self.label_86.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_86, 0, 0, 1, 1)

        self.label_81 = QLabel(self.layoutWidget_3)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_81, 6, 1, 1, 1)

        self.label_84 = QLabel(self.layoutWidget_3)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_84, 2, 0, 1, 1)

        self.label_91 = QLabel(self.layoutWidget_3)
        self.label_91.setObjectName(u"label_91")
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette3.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette3.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette3.setBrush(QPalette.Active, QPalette.Mid, brush11)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette3.setBrush(QPalette.Active, QPalette.Shadow, brush12)
        palette3.setBrush(QPalette.Active, QPalette.Highlight, brush15)
        palette3.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Active, QPalette.Link, brush16)
        palette3.setBrush(QPalette.Active, QPalette.LinkVisited, brush17)
        palette3.setBrush(QPalette.Active, QPalette.AlternateBase, brush13)
        palette3.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette3.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette3.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Link, brush16)
        palette3.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush17)
        palette3.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        brush23 = QBrush(QColor(0, 0, 0, 255))
        brush23.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Inactive, QPalette.NoRole, brush23)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Midlight, brush21)
        palette3.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Mid, brush11)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette3.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette3.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Highlight, brush15)
        palette3.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Link, brush16)
        palette3.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush17)
        palette3.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        brush24 = QBrush(QColor(0, 0, 0, 255))
        brush24.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Disabled, QPalette.NoRole, brush24)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette3.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush18)
#endif
        self.label_91.setPalette(palette3)
        self.label_91.setFont(font)
        self.label_91.setFrameShape(QFrame.NoFrame)
        self.label_91.setTextFormat(Qt.MarkdownText)
        self.label_91.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label_91, 0, 1, 1, 1)

        self.label_75 = QLabel(self.layoutWidget_3)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setFont(font)
        self.label_75.setAlignment(Qt.AlignCenter)
        self.label_75.setWordWrap(True)

        self.gridLayout_4.addWidget(self.label_75, 0, 2, 1, 1)

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.layoutWidget = QWidget(self.tab_3)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 10, 611, 311))
        self.gridLayout_3 = QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_70 = QLabel(self.layoutWidget)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_70, 2, 0, 1, 1)

        self.label_64 = QLabel(self.layoutWidget)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_64, 6, 0, 1, 1)

        self.label_54 = QLabel(self.layoutWidget)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_54, 3, 2, 1, 1)

        self.label_69 = QLabel(self.layoutWidget)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_69, 6, 1, 1, 1)

        self.label_72 = QLabel(self.layoutWidget)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_72, 5, 2, 1, 1)

        self.label_56 = QLabel(self.layoutWidget)
        self.label_56.setObjectName(u"label_56")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette4.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette4.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette4.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.label_56.setPalette(palette4)
        self.label_56.setFont(font)
        self.label_56.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_56, 0, 0, 1, 1)

        self.label_51 = QLabel(self.layoutWidget)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_51, 4, 1, 1, 1)

        self.label_59 = QLabel(self.layoutWidget)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_59, 6, 2, 1, 1)

        self.label_61 = QLabel(self.layoutWidget)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_61, 3, 0, 1, 1)

        self.label_49 = QLabel(self.layoutWidget)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_49, 5, 0, 1, 1)

        self.label_71 = QLabel(self.layoutWidget)
        self.label_71.setObjectName(u"label_71")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette5.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Active, QPalette.Mid, brush11)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette5.setBrush(QPalette.Active, QPalette.Shadow, brush12)
        palette5.setBrush(QPalette.Active, QPalette.Highlight, brush15)
        palette5.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Link, brush16)
        palette5.setBrush(QPalette.Active, QPalette.LinkVisited, brush17)
        palette5.setBrush(QPalette.Active, QPalette.AlternateBase, brush13)
        palette5.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette5.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette5.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette5.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Link, brush16)
        palette5.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush17)
        palette5.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        brush25 = QBrush(QColor(0, 0, 0, 255))
        brush25.setStyle(Qt.NoBrush)
        palette5.setBrush(QPalette.Inactive, QPalette.NoRole, brush25)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
#endif
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette5.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Midlight, brush21)
        palette5.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Mid, brush11)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette5.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.Highlight, brush15)
        palette5.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette5.setBrush(QPalette.Disabled, QPalette.Link, brush16)
        palette5.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush17)
        palette5.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        brush26 = QBrush(QColor(0, 0, 0, 255))
        brush26.setStyle(Qt.NoBrush)
        palette5.setBrush(QPalette.Disabled, QPalette.NoRole, brush26)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush18)
#endif
        self.label_71.setPalette(palette5)
        self.label_71.setFont(font)
        self.label_71.setFrameShape(QFrame.NoFrame)
        self.label_71.setTextFormat(Qt.MarkdownText)
        self.label_71.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_71, 0, 1, 1, 1)

        self.label_57 = QLabel(self.layoutWidget)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setFont(font)
        self.label_57.setAlignment(Qt.AlignCenter)
        self.label_57.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_57, 0, 2, 1, 1)

        self.label_58 = QLabel(self.layoutWidget)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_58, 3, 1, 1, 1)

        self.label_63 = QLabel(self.layoutWidget)
        self.label_63.setObjectName(u"label_63")
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setScaledContents(False)
        self.label_63.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_63, 1, 0, 1, 1)

        self.label_68 = QLabel(self.layoutWidget)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_68, 5, 1, 1, 1)

        self.label_52 = QLabel(self.layoutWidget)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_52, 4, 0, 1, 1)

        self.label_66 = QLabel(self.layoutWidget)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_66, 1, 2, 1, 1)

        self.label_60 = QLabel(self.layoutWidget)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setScaledContents(True)
        self.label_60.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_60, 2, 1, 1, 1)

        self.label_62 = QLabel(self.layoutWidget)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_62, 2, 2, 1, 1)

        self.label_65 = QLabel(self.layoutWidget)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setScaledContents(True)
        self.label_65.setWordWrap(True)

        self.gridLayout_3.addWidget(self.label_65, 1, 1, 1, 1)

        self.label_50 = QLabel(self.layoutWidget)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setAlignment(Qt.AlignCenter)

        self.gridLayout_3.addWidget(self.label_50, 4, 2, 1, 1)

        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.layoutWidget_4 = QWidget(self.tab_4)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(10, 10, 611, 311))
        self.gridLayout_6 = QGridLayout(self.layoutWidget_4)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_136 = QLabel(self.layoutWidget_4)
        self.label_136.setObjectName(u"label_136")
        self.label_136.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_136, 5, 0, 1, 1)

        self.label_121 = QLabel(self.layoutWidget_4)
        self.label_121.setObjectName(u"label_121")
        self.label_121.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_121.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_121, 2, 2, 1, 1)

        self.label_126 = QLabel(self.layoutWidget_4)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_126.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_126, 5, 2, 1, 1)

        self.label_125 = QLabel(self.layoutWidget_4)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setFont(font)
        self.label_125.setStyleSheet(u"background-color : rgba(255, 170, 0, 150)")
        self.label_125.setFrameShape(QFrame.NoFrame)
        self.label_125.setFrameShadow(QFrame.Plain)
        self.label_125.setLineWidth(1)
        self.label_125.setScaledContents(False)
        self.label_125.setAlignment(Qt.AlignCenter)
        self.label_125.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_125, 2, 1, 1, 1)

        self.label_139 = QLabel(self.layoutWidget_4)
        self.label_139.setObjectName(u"label_139")
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush9)
        palette6.setBrush(QPalette.Active, QPalette.Light, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Active, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Active, QPalette.Mid, brush11)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush14)
        palette6.setBrush(QPalette.Active, QPalette.Shadow, brush12)
        palette6.setBrush(QPalette.Active, QPalette.Highlight, brush15)
        palette6.setBrush(QPalette.Active, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Active, QPalette.Link, brush16)
        palette6.setBrush(QPalette.Active, QPalette.LinkVisited, brush17)
        palette6.setBrush(QPalette.Active, QPalette.AlternateBase, brush13)
        palette6.setBrush(QPalette.Active, QPalette.NoRole, brush)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette6.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush18)
#endif
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette6.setBrush(QPalette.Inactive, QPalette.Highlight, brush9)
        palette6.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Link, brush16)
        palette6.setBrush(QPalette.Inactive, QPalette.LinkVisited, brush17)
        palette6.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        brush27 = QBrush(QColor(0, 0, 0, 255))
        brush27.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Inactive, QPalette.NoRole, brush27)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette6.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
#endif
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush20)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush9)
        palette6.setBrush(QPalette.Disabled, QPalette.Light, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Midlight, brush21)
        palette6.setBrush(QPalette.Disabled, QPalette.Dark, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Mid, brush11)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush20)
        palette6.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush20)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush14)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush14)
        palette6.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Highlight, brush15)
        palette6.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Link, brush16)
        palette6.setBrush(QPalette.Disabled, QPalette.LinkVisited, brush17)
        palette6.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        brush28 = QBrush(QColor(0, 0, 0, 255))
        brush28.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Disabled, QPalette.NoRole, brush28)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette6.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush18)
#endif
        self.label_139.setPalette(palette6)
        self.label_139.setFont(font)
        self.label_139.setFrameShape(QFrame.NoFrame)
        self.label_139.setTextFormat(Qt.MarkdownText)
        self.label_139.setAlignment(Qt.AlignCenter)

        self.gridLayout_6.addWidget(self.label_139, 0, 1, 1, 1)

        self.label_143 = QLabel(self.layoutWidget_4)
        self.label_143.setObjectName(u"label_143")
        sizePolicy.setHeightForWidth(self.label_143.sizePolicy().hasHeightForWidth())
        self.label_143.setSizePolicy(sizePolicy)
        self.label_143.setScaledContents(False)
        self.label_143.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_143, 1, 0, 1, 1)

        self.label_144 = QLabel(self.layoutWidget_4)
        self.label_144.setObjectName(u"label_144")
        self.label_144.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_144.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_144, 1, 2, 1, 1)

        self.label_135 = QLabel(self.layoutWidget_4)
        self.label_135.setObjectName(u"label_135")
        self.label_135.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_135, 4, 0, 1, 1)

        self.label_122 = QLabel(self.layoutWidget_4)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_122, 3, 0, 1, 1)

        self.label_124 = QLabel(self.layoutWidget_4)
        self.label_124.setObjectName(u"label_124")
        self.label_124.setEnabled(True)
        self.label_124.setFont(font)
        self.label_124.setStyleSheet(u"background-color : rgba(255, 255, 0, 150)")
        self.label_124.setAlignment(Qt.AlignCenter)
        self.label_124.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_124, 3, 1, 1, 1)

        self.label_123 = QLabel(self.layoutWidget_4)
        self.label_123.setObjectName(u"label_123")
        self.label_123.setFont(font)
        self.label_123.setAlignment(Qt.AlignCenter)
        self.label_123.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_123, 0, 2, 1, 1)

        self.label_142 = QLabel(self.layoutWidget_4)
        self.label_142.setObjectName(u"label_142")
        self.label_142.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_142.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_142, 4, 2, 1, 1)

        self.label_132 = QLabel(self.layoutWidget_4)
        self.label_132.setObjectName(u"label_132")
        self.label_132.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_132, 2, 0, 1, 1)

        self.label_131 = QLabel(self.layoutWidget_4)
        self.label_131.setObjectName(u"label_131")
        self.label_131.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_131.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_131, 3, 2, 1, 1)

        self.label_127 = QLabel(self.layoutWidget_4)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setFont(font)
        self.label_127.setStyleSheet(u"background-color : rgba(0, 170, 0, 150)")
        self.label_127.setAlignment(Qt.AlignCenter)
        self.label_127.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_127, 5, 1, 1, 1)

        self.label_137 = QLabel(self.layoutWidget_4)
        self.label_137.setObjectName(u"label_137")
        self.label_137.setFont(font)
        self.label_137.setAutoFillBackground(False)
        self.label_137.setStyleSheet(u"background-color : rgba(255, 0, 0, 150)")
        self.label_137.setFrameShape(QFrame.NoFrame)
        self.label_137.setScaledContents(False)
        self.label_137.setAlignment(Qt.AlignCenter)
        self.label_137.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_137, 1, 1, 1, 1)

        self.label_138 = QLabel(self.layoutWidget_4)
        self.label_138.setObjectName(u"label_138")
        self.label_138.setFont(font)
        self.label_138.setStyleSheet(u"background-color : rgba(187, 255, 0, 150)")
        self.label_138.setAlignment(Qt.AlignCenter)
        self.label_138.setWordWrap(True)

        self.gridLayout_6.addWidget(self.label_138, 4, 1, 1, 1)

        self.label_134 = QLabel(self.layoutWidget_4)
        self.label_134.setObjectName(u"label_134")
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush)
        palette7.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette7.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette7.setBrush(QPalette.Active, QPalette.AlternateBase, brush7)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Button, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.Light, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Midlight, brush10)
        palette7.setBrush(QPalette.Inactive, QPalette.Dark, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.Mid, brush11)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette7.setBrush(QPalette.Inactive, QPalette.Window, brush9)
        palette7.setBrush(QPalette.Inactive, QPalette.Shadow, brush12)
        palette7.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush13)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette7.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette7.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette7.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette7.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette7.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush13)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush8)
        palette7.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.label_134.setPalette(palette7)
        self.label_134.setFont(font)
        self.label_134.setAlignment(Qt.AlignCenter)

        self.gridLayout_6.addWidget(self.label_134, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_4, "")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(660, 10, 311, 361))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.groupBox.setFont(font1)
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 50, 291, 22))
        font2 = QFont()
        font2.setPointSize(8)
        font2.setBold(False)
        self.comboBox.setFont(font2)
        self.comboBox_2 = QComboBox(self.groupBox)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(10, 110, 291, 22))
        self.comboBox_2.setFont(font2)
        self.comboBox_3 = QComboBox(self.groupBox)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(10, 170, 291, 22))
        self.comboBox_3.setFont(font2)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 30, 191, 16))
        self.label.setFont(font1)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 90, 191, 16))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 150, 191, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 240, 201, 41))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(True)
        self.label_4.setFont(font3)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_reponse = QLabel(self.groupBox)
        self.label_reponse.setObjectName(u"label_reponse")
        self.label_reponse.setGeometry(QRect(20, 290, 201, 41))
        font4 = QFont()
        font4.setPointSize(14)
        font4.setBold(True)
        self.label_reponse.setFont(font4)
        self.label_reponse.setFrameShape(QFrame.Box)
        self.label_reponse.setFrameShadow(QFrame.Raised)
        self.label_reponse.setWordWrap(True)
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(100, 210, 121, 24))
        self.code_couleur = QFrame(self.groupBox)
        self.code_couleur.setObjectName(u"code_couleur")
        self.code_couleur.setGeometry(QRect(250, 290, 41, 41))
        self.code_couleur.setStyleSheet(u"background-color : white")
        self.code_couleur.setFrameShape(QFrame.Box)
        self.code_couleur.setFrameShadow(QFrame.Sunken)
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.tabWidget, self.comboBox)
        QWidget.setTabOrder(self.comboBox, self.comboBox_2)
        QWidget.setTabOrder(self.comboBox_2, self.comboBox_3)
        QWidget.setTabOrder(self.comboBox_3, self.pushButton)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.calculate)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Calculator", None))
        self.label_106.setText(QCoreApplication.translate("MainWindow", u"0,1", None))
        self.label_97.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_98.setText(QCoreApplication.translate("MainWindow", u"Inhabituel mais possible", None))
        self.label_102.setText(QCoreApplication.translate("MainWindow", u"0,5", None))
        self.label_110.setText(QCoreApplication.translate("MainWindow", u"Facteur", None))
        self.label_117.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>On ne sait jamais, mais les risques sont tellement infimes que ce cas de figure n\u2019est pas r\u00e9aliste.</p></body></html>", None))
        self.label_112.setText(QCoreApplication.translate("MainWindow", u"Imaginable mais tr\u00e8s improbable", None))
        self.label_118.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_103.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L\u2019accident pourrait survenir si tout allait de travers en m\u00eame temps.</p></body></html>", None))
        self.label_107.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_115.setText(QCoreApplication.translate("MainWindow", u"Interpr\u00e9tation", None))
        self.label_104.setText(QCoreApplication.translate("MainWindow", u"Virtuellement impossible", None))
        self.label_99.setText(QCoreApplication.translate("MainWindow", u"P", None))
        self.label_100.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L\u2019accident peut survenir, mais les risques qu\u2019il survienne ne sont pas si grands.</p></body></html>", None))
        self.label_116.setText(QCoreApplication.translate("MainWindow", u"0,2", None))
        self.label_109.setText(QCoreApplication.translate("MainWindow", u"Pratiquement impossible", None))
        self.label_101.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Les risques que l\u2019accident survienne sont (plus que) grands.</p></body></html>", None))
        self.label_105.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Th\u00e9oriquement parlant, il reste envisageable qu\u2019un probl\u00e8me survienne.</p></body></html>", None))
        self.label_120.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_114.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L\u2019accident peut survenir si plusieurs probl\u00e8mes surviennent simultan\u00e9ment.</p></body></html>", None))
        self.label_119.setText(QCoreApplication.translate("MainWindow", u"Pr\u00e9visible", None))
        self.label_108.setText(QCoreApplication.translate("MainWindow", u"Fort probable", None))
        self.label_111.setText(QCoreApplication.translate("MainWindow", u"Uniquement possible dans un cas limite", None))
        self.label_113.setText(QCoreApplication.translate("MainWindow", u"Ce n\u2019est qu\u2019une question de temps avant que l\u2019accident survienne.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Facteur de probabilit\u00e9", None))
        self.label_89.setText(QCoreApplication.translate("MainWindow", u"4 \u2013 8 heures/jour ou > 200 op\u00e9rations par jour", None))
        self.label_94.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_78.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_76.setText(QCoreApplication.translate("MainWindow", u"1 \u2013 2,5 heure(s)/semaine ou 20 \u2013 200 op\u00e9rations par semaine", None))
        self.label_96.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_77.setText(QCoreApplication.translate("MainWindow", u"30 min \u2013 4 heures/jour ou 20 \u2013 200 op\u00e9rations par jour", None))
        self.label_74.setText(QCoreApplication.translate("MainWindow", u"Occasionnel (1x/semaine)", None))
        self.label_83.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_85.setText(QCoreApplication.translate("MainWindow", u"Tr\u00e8s rare (1x/an)", None))
        self.label_90.setText(QCoreApplication.translate("MainWindow", u"20 min \u2013 1 heure/semaine ou 2 \u2013 20 op\u00e9rations par semaine", None))
        self.label_79.setText(QCoreApplication.translate("MainWindow", u"4 \u2013 16 heures/an ou 5 \u2013 100 op\u00e9rations par an", None))
        self.label_87.setText(QCoreApplication.translate("MainWindow", u"Inhabituel (1x/mois)", None))
        self.label_95.setText(QCoreApplication.translate("MainWindow", u"Permanent", None))
        self.label_88.setText(QCoreApplication.translate("MainWindow", u"Rare (2-3x/an)", None))
        self.label_73.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_92.setText(QCoreApplication.translate("MainWindow", u"0,5", None))
        self.label_86.setText(QCoreApplication.translate("MainWindow", u"Facteur", None))
        self.label_81.setText(QCoreApplication.translate("MainWindow", u"< 4 heures/an ou < 5 op\u00e9rations par an", None))
        self.label_84.setText(QCoreApplication.translate("MainWindow", u"Fr\u00e9quent (1x/jour)", None))
        self.label_91.setText(QCoreApplication.translate("MainWindow", u"Interpr\u00e9tation", None))
        self.label_75.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Niveau d\u2019exposition", None))
        self.label_70.setText(QCoreApplication.translate("MainWindow", u"Tragique", None))
        self.label_64.setText(QCoreApplication.translate("MainWindow", u"Minime", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.label_69.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L\u00e9sion n\u00e9cessitant des soins jusqu\u2019\u00e0 une tr\u00e8s br\u00e8ve incapacit\u00e9</p></body></html>", None))
        self.label_72.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Facteur", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>L\u00e9sion avec longue incapacit\u00e9 ou l\u00e9sion permanente</p></body></html>", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Tr\u00e8s grave", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Important", None))
        self.label_71.setText(QCoreApplication.translate("MainWindow", u"Interpr\u00e9tation", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Tr\u00e8s grave, l\u00e9sion permanente ou accident mortel</p></body></html>", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"Catastrophique", None))
        self.label_68.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Incapacit\u00e9 de travail (&gt; quelques jours et &lt; des mois)</p></body></html>", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Grave", None))
        self.label_66.setText(QCoreApplication.translate("MainWindow", u"100", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Perte de plusieurs vies humaines</p></body></html>", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"40", None))
        self.label_65.setText(QCoreApplication.translate("MainWindow", u"Perte de nombreuses vies humaines", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Niveau des dommages", None))
        self.label_136.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.label_121.setText(QCoreApplication.translate("MainWindow", u"Elev\u00e9, \u00e0 am\u00e9liorer imm\u00e9diatement", None))
        self.label_126.setText(QCoreApplication.translate("MainWindow", u"Risque, peut-\u00eatre acceptable", None))
        self.label_125.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_139.setText(QCoreApplication.translate("MainWindow", u"Priorit\u00e9 (p)", None))
        self.label_143.setText(QCoreApplication.translate("MainWindow", u"> 400", None))
        self.label_144.setText(QCoreApplication.translate("MainWindow", u"Tr\u00e8s \u00e9lev\u00e9, inacceptable, arr\u00eat envisag\u00e9", None))
        self.label_135.setText(QCoreApplication.translate("MainWindow", u"21 \u2013 70", None))
        self.label_122.setText(QCoreApplication.translate("MainWindow", u"71 \u2013 200", None))
        self.label_124.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_123.setText(QCoreApplication.translate("MainWindow", u"Risque", None))
        self.label_142.setText(QCoreApplication.translate("MainWindow", u"Possible, attention n\u00e9cessaire", None))
        self.label_132.setText(QCoreApplication.translate("MainWindow", u"201 \u2013 400", None))
        self.label_131.setText(QCoreApplication.translate("MainWindow", u"Important, am\u00e9lioration n\u00e9cessaire", None))
        self.label_127.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_137.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_138.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_134.setText(QCoreApplication.translate("MainWindow", u"Chiffre attribu\u00e9 au risque (R)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Chiffre attribu\u00e9 au risque", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Calcul", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Pr\u00e9visible", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Fort probable", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Inhabituel mais possible", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Uniquement possible dans un cas limite", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"Imaginable mais tr\u00e8s improbable", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"Pratiquement impossible", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"Pratiquement impossible", None))

        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Permanent", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Fr\u00e9quent (1x/jour)", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Occasionnel (1x/semaine)", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"Inhabituel (1x/mois)", None))
        self.comboBox_2.setItemText(4, QCoreApplication.translate("MainWindow", u"Rare (2-3x/an)", None))
        self.comboBox_2.setItemText(5, QCoreApplication.translate("MainWindow", u"Tr\u00e8s rare (1x/an)", None))

        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Catastrophique", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"Tragique", None))
        self.comboBox_3.setItemText(2, QCoreApplication.translate("MainWindow", u"Tr\u00e8s grave", None))
        self.comboBox_3.setItemText(3, QCoreApplication.translate("MainWindow", u"Grave", None))
        self.comboBox_3.setItemText(4, QCoreApplication.translate("MainWindow", u"Important", None))
        self.comboBox_3.setItemText(5, QCoreApplication.translate("MainWindow", u"Minime", None))

        self.label.setText(QCoreApplication.translate("MainWindow", u"Facteur de probabilit\u00e9 (P) ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Facteur d\u2019exposition (E)", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Degr\u00e9 de gravit\u00e9 (G)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"R = P x E x G", None))
        self.label_reponse.setText(QCoreApplication.translate("MainWindow", u"R =", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Calculer", None))
    # retranslateUi

